In [1]:
import pandas as pd
import numpy as np
import os
import random
import deepchem as dc
import tensorflow as tf

Skipped loading some Pytorch utilities, missing a dependency. No module named 'torch'


This module requires PyTorch to be installed.


No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!


Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


Skipped loading some PyTorch models, missing a dependency. No module named 'torch'
No module named 'torch'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch'
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'torch'
Skipped loading some Jax models, missing a dependency. No module named 'jax'


In [ ]:
#Getting the delaney dataset of solubility from deepchem. All have valid solubility measurements so weights are 1

In [2]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer="GraphConv", splitter="random")
train_dataset, valid_dataset, test_dataset = datasets
print(train_dataset)

<DiskDataset X.shape: (np.int64(902),), y.shape: (np.int64(902), np.int64(1)), w.shape: (np.int64(902), np.int64(1)), ids: ['CN(C)C(=O)C(c1ccccc1)c2ccccc2 ' 'CCOC(=O)c1ccc(N)cc1'
 'FC(F)(Cl)C(F)(F)Cl' ... 'Cc1ccc(O)c(C)c1' 'CCSC(=O)N(CC(C)C)CC(C)C'
 'Cn1c(=O)n(C)c2nc[nH]c2c1=O'], task_names: ['measured log solubility in mols per litre']>


In [3]:
train_dataframe = train_dataset.to_dataframe()

In [4]:
train_dataframe

X         y    w  \
0    <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.038124  1.0   
1    <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.210134  1.0   
2    <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.151537  1.0   
3    <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.764750  1.0   
4    <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.283853  1.0   
..                                                 ...       ...  ...   
897  <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.694339  1.0   
898  <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.272512  1.0   
899  <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.884000  1.0   
900  <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.292666  1.0   
901  <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.789489  1.0   

                                           ids  
0               CN(C)C(=O)C(c1ccccc1)c2ccccc2   
1                          CCOC(=O)c1ccc(N)cc1  
2                           FC(F)(Cl)C(F)(F)Cl  
3                           Cc1cccc2c(C)cccc12  
4                          CC(C)=CCC/C(C)=C\CO  
..                                         ...  
897  c1ccc(Cl)cc1C(c2ccc(Cl)cc2)(O)C(=O)OC(C)C  
898           Cc1[nH]c(=O)n(c(=O)c1Cl)C(C)(C)C  
899                            Cc1ccc(O)c(C)c1  
900                    CCSC(=O)N(CC(C)C)CC(C)C  
901                 Cn1c(=O)n(C)c2nc[nH]c2c1=O  

[902 rows x 4 columns]

In [ ]:
#So now I need to extract the SMILES strings from the dataset
#So inputs need to be made a fixed size
#Featurising converts smiles into numeric, measuring interactions, etc. 

In [5]:
from rdkit import Chem
print(dc.__version__)

2.8.0


In [6]:
from platform import python_version

print(python_version())

3.9.23


In [7]:
smiles = train_dataframe["ids"] 

In [8]:
print(smiles)

0                 CN(C)C(=O)C(c1ccccc1)c2ccccc2 
1                            CCOC(=O)c1ccc(N)cc1
2                             FC(F)(Cl)C(F)(F)Cl
3                             Cc1cccc2c(C)cccc12
4                            CC(C)=CCC/C(C)=C\CO
                         ...                    
897    c1ccc(Cl)cc1C(c2ccc(Cl)cc2)(O)C(=O)OC(C)C
898             Cc1[nH]c(=O)n(c(=O)c1Cl)C(C)(C)C
899                              Cc1ccc(O)c(C)c1
900                      CCSC(=O)N(CC(C)C)CC(C)C
901                   Cn1c(=O)n(C)c2nc[nH]c2c1=O
Name: ids, Length: 902, dtype: object


In [9]:
featurizer = dc.feat.CircularFingerprint(size=2048, radius=4)
features = featurizer.featurize(smiles)

[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:24] DEPRECATION WARNING: please use MorganGenerator
[13:17:25] DEPRECATION WARNING: please use MorganGenerator
[13:17:25] DEPRECATION WARNING: please use MorganGenerat

In [25]:
seed = random.seed(400)

In [23]:
#Have now featurized my SMILES data

In [25]:
#Now need to take the target solubility values. Solubility is Log valued 

In [12]:
solubility= train_dataframe["y"] 

In [ ]:
#smiles, features, solubility 

In [ ]:
#So now I need to Train test and split the data to determine how my model performs on new data

In [13]:
X = features

In [23]:
y = solubility

In [22]:
print(X)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#Can either do random split or a scaffold split. Going to random using scikit learn

In [15]:
from sklearn.model_selection import train_test_split

In [ ]:
#Need to preserve alignment, so done together 

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=seed)

In [ ]:
#so data is split into training and test datasets

In [38]:
from sklearn.datasets import make_regression

In [39]:
from sklearn.ensemble import GradientBoostingRegressor 

In [43]:
from sklearn.model_selection import cross_val_score

In [ ]:
#GBR used because my target y is a number and continous 

In [40]:
reg = GradientBoostingRegressor(random_state=seed)

In [41]:
reg.fit(X_train, y_train)

GradientBoostingRegressor()

In [ ]:
#My R2 value, tells me how well my model explains variance in solubility. Currently poorly 

In [45]:
cross_val_score(reg, X_train, y_train, cv=3, n_jobs=-1).mean()

np.float64(0.5602531865141239)

In [ ]:
#Hyperparametere tuning 

In [ ]:
#n_estimators number of trees, too few underfit, too many overfit
#learning_rate. How much each tree contributes to correcting errors
#max_depth maximum depth of each individual tree. Shallow udnerfit. Deep overfit
#min samples split. Minimum numbers of samples required to split a node
#min samples leaf. Minimum number of samples erquired to split a node
#subsample. Fraction of training data used for each tree

In [57]:
param_grid = {
    "n_estimators": [10, 50, 100, 500],
    "learning_rate": [0.0001, 0.001, 0.01, 0.1, 1.0],
    "max_depth":[3, 5, 7, 9]
}

In [47]:
from sklearn.model_selection import GridSearchCV

In [49]:
reg2 = GridSearchCV(reg, param_grid, cv=3, n_jobs=-1)

In [51]:
reg2.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.0001, 0.001, 0.01, 0.1, 1.0],
                         'max_depth': [3, 5, 7, 9],
                         'n_estimators': [10, 50, 100, 500]})

In [53]:
reg2.best_params_

{'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 500}

In [54]:
reg2.best_score_

np.float64(0.6392190276464119)

In [58]:
param_grid_2 = {
    "min_samples_leaf": [1, 2, 3, 4, 5],
    "min_samples_split": [2, 4, 6, 8, 10], 
    "subsample": [0.6, 0.7, 0.8, 0.9, 1.0]
}

In [59]:
reg3 = GridSearchCV(reg, param_grid_2, cv=3, n_jobs=-1)

In [60]:
reg3.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 4, 6, 8, 10],
                         'subsample': [0.6, 0.7, 0.8, 0.9, 1.0]})

In [61]:
reg3.best_params_

{'min_samples_leaf': 4, 'min_samples_split': 4, 'subsample': 0.7}

In [62]:
reg3.best_score_

np.float64(0.6212215879679739)

In [70]:
param_grid_3 = {
    "n_estimators": [10, 25, 50, 75, 100, 200, 300, 400, 500],
    "learning_rate": [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
    "max_depth": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "min_samples_leaf": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "min_samples_split": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "subsample": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
}

In [71]:
reg4 = GridSearchCV(reg, param_grid_3, cv=3, n_jobs=-1)

In [72]:
reg4.fit(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
reg4.best_params_

In [ ]:
reg4.best_score_